### ISSUE TITLE
Support folders

### ISSUE THREAD

**Issue by weiran** [weiran/watch-it-later#1]

**Comment by trijste** [comment]
Hi, I am new to this app and thought I would collect saved videos into a folder (separate from my main feed). Unfortunately, Watch it Later cannot find them in my folder.

I see this is an issue you're aware of. Is there no way to allow specific folder selection in the app, or else provide access to saved links across folders?

Thanks for the great app regardless, btw :)

**Comment by weiran** [comment]
@trijste yep this feature is next on the list 👍

**Comment by weiran** [comment]
@trijste you'll be happy to hear that the next 2.0 update will finally add support for folders!

See #31.

**Comment by trijste** [comment]
Woooooooooow!!!! ❤️❤️❤️
